meditrack/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("meds.urls")),
]

meds/urls.py
from django.urls import path

from .views import HomePageView, MedicationListView, LogCreateView, LogListView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("meds/", MedicationListView.as_view(), name="med_list"),
    path("logs/create/", LogCreateView.as_view(), name="log_create"),
    path("logs/", LogListView.as_view(), name="log_list"),
]

app_name = "meds"

meds/models.py
from django.db import models


class Perscription(models.Model):
    """Perscription model."""

    name = models.CharField(max_length=100)
    dosage = models.PositiveIntegerField()
    interval = models.DurationField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def last_taken(self: "Perscription") -> str:
        """Return the last time the perscription was taken."""
        if self.log_set.count() == 0:
            return "Never"
        return self.log_set.last().created_at

    @property
    def next_dose(self: "Perscription") -> str:
        """Return the next time the perscription should be taken."""
        if self.log_set.count() == 0:
            return "Whenever"
        return self.log_set.last().created_at + self.interval

    def __str__(self: "Perscription") -> str:
        """Return a string representation of the model."""
        return self.name


class Log(models.Model):
    """Log model."""

    perscription = models.ForeignKey(Perscription, on_delete=models.CASCADE)
    taken = models.BooleanField(default=False)
    notes = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self: "Log") -> str:
        """Return a string representation of the model."""
        return f"{self.perscription.name} - {self.created_at}"

meds/views.py
from typing import Any
from django.views.generic import TemplateView, ListView, CreateView

from .models import Perscription, Log


class HomePageView(TemplateView):
    """Home page view."""

    template_name = "home.html"


class MedicationListView(ListView):
    """List all perscriptions."""

    template_name = "meds/med_list.html"
    model = Perscription


class LogCreateView(CreateView):
    """Create a new log entry for a perscription."""

    template_name = "meds/log_create.html"
    model = Log
    fields = ("perscription", "taken", "notes")

    def get_initial(self) -> dict[str, Any]:
        """Get initial data for the form. Sets perscription to the GET param."""
        data = super().get_initial()
        if self.request.GET.get("perscription"):
            data["perscription"] = self.request.GET.get("perscription")
        return data


class LogListView(ListView):
    """List all logs."""

    template_name = "meds/log_list.html"
    model = Log

    def get_queryset(self):
        """Get the queryset for the view. Can filter by perscription id."""
        qs = super().get_queryset()
        if self.request.GET.get("perscription"):
            qs = qs.filter(perscription_id=self.request.GET.get("perscription"))
        return qs

meditrack/templates/base.html
{% load static django_htmx %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="HTMX Testing site">
        <meta name="keywords" content="HTML, CSS, JavaScript, HTMX, Bootstrap">
        <title>Meditrack</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
              crossorigin="anonymous">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
        <script src="{% static 'htmx.min.js' %}"></script>
        <script src="https://unpkg.com/htmx.org/dist/ext/debug.js" defer></script>
        {% django_htmx_script %}
    </head>
    <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
        {% block body %}
            <h1>Hello, world!</h1>
        {% endblock body %}
        {% comment %} <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script> {% endcomment %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"
                integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"
                crossorigin="anonymous"></script>
    </body>
</html>

meds/templates/home.html
{% extends "base.html" %}
{% block body %}
<div class="container">
    <h1>MediTrack</h1>
    <div hx-get="{% url 'meds:med_list' %}" hx-trigger="load">Med List</div>
    <div id="form-holder"></div>
</div>
{% endblock body %}

meds/templates/meds/log_create.html
{% load crispy_forms_tags %}
{{ form | crispy }}

meds/templates/meds/log_list.html
{% for log in object_list %}
    <div>
        <h1>{{ log }}</h1>
        <ul>
            <li>perscription: {{ log.perscription }}</li>
            <li>taken: {{ log.taken }}</li>
            <li>created_at: {{ log.created_at }}</li>
            <li>updated_at: {{ log.updated_at }}</li>
            <li>notes: {{ log.notes }}</li>
        </ul>
    </div>
{% endfor %}

meds/templates/meds/med_list.html
{% load humanize %}
<table class="table">
    <thead>
        <tr>
            <th>Med Name</th>
            <th>Last Taken</th>
            <th>When you can take next</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for med in object_list %}
        <tr>
            <td>{{med.name}}</td>
            <td title="{{med.last_taken}}">{{med.last_taken | naturaltime}}</td>
            <td title="{{med.next_dose}}">{{med.next_dose | naturaltime}}</td>
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <button class="btn btn-success" hx-get="{% url 'meds:log_create' %}?perscription={{med.id}}"
                        hx-target="#form-holder"><i class="bi bi-file-earmark-plus"></i></button>
                    <button class="btn btn-info" hx-get="{% url 'meds:log_list' %}?perscription={{med.id}}"
                        hx-target="#form-holder"><i class="bi bi-journal-medical"></i></button>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>